
PATH:
  DATA_ROOT: C:\Users\test\Desktop\Leon\Datasets\LIDC-preprocess
  SAVE_ROOT: C:\Users\test\Desktop\Leon\Datasets\LIDC-preprocess

TASK_NAME: Nodule_Detection

CATEGORY_ID:
  Nodule_Detection:
    Nodule: 1
  
  Malignancy:
    Benign: 1
    Malignant: 2

AREA_THRESHOLD: 8  

SPLIT:
  Train: 0.7
  Valid: 0.1
  Test: 0.2

CROSS_VALID_FOLD: 5