CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_011\ckpt_best.pth
CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_012\ckpt_best.pth
CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_000\ckpt_best.pth
CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_001\ckpt_best.pth
CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_004\ckpt_best.pth
CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_006\ckpt_best.pth
# CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_008\ckpt_best.pth
# CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_009\ckpt_best.pth
CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_010\ckpt_best.pth
# CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_013\ckpt_best.pth
# CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_014\ckpt_best.pth
# CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_015\ckpt_best.pth
# CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_016\ckpt_best.pth
CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_019\ckpt_best.pth
# CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_020\ckpt_best.pth
# CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_021\ckpt_best.pth
# CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_022\ckpt_best.pth
# CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_023\ckpt_best.pth
CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_027\ckpt_best.pth
CHECKPOINT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2\checkpoints\run_033\ckpt_best.pth
DATA:
  BATCH_SIZE: 1
  DATA_PATH: 
    LUNA16: C:\Users\test\Desktop\Leon\Datasets\LUNA16-preprocess\crop
    ASUS-B: C:\Users\test\Desktop\Leon\Datasets\ASUS_Nodules-preprocess\benign_merge\crop
    ASUS-M: C:\Users\test\Desktop\Leon\Datasets\ASUS_Nodules-preprocess\malignant_merge\crop
  CROP_RANGE:
    index: 48
    row: 48
    column: 48
  SHUFFLE: False
  NPratio: 10
  NPratio_test: 10
  NAME:
    # - LUNA16
    - ASUS-B
    - ASUS-M
MODEL:
  # NAME: resnet50
  ACTIVATION: softmax
  NUM_CLASSES: 2
  DEPTH: 50

TRAIN:
  PROJECT_PATH: C:\Users\test\Desktop\Leon\Projects\detectron2
  manual_seed: 0


